### PR TITLE
Master

### PR DESCRIPTION
**Pull request by juek**
2 suggestions

### CODE REVIEW

**Comment by juek** [comment]
sorry for the revert mess ;)

**Comment by mahotilo** [comment]
Thx

**Comment by mahotilo** [comment]
> omit closing ?> PHP tag

Have been inherited from DockableAdminPanel plugin used as a donor:)
I know that this is a kind of "good practice", but so unusual for me after "traditional" languages.

**Comment by juek** [comment]
> I know that this is a kind of "good practice", but so unusual for me after "traditional" languages.

It's simply due to PHP's dirty habit to output everything outside its tags, including whitespace. Therefore we cannot obey to the coding standard 'Newline at end of file' when using closing tags.

**Pull request merged**
